### ISSUE TITLE
Add support for MAD sector

### ISSUE THREAD

**Issue by eximius313** [nfcim/ndef#16]
Could you also support reading of [Mifare Application Directory](https://www.nxp.com/docs/en/application-note/AN10787.pdf) `MAD` (sector 0), [as it indicates the sector that contains NDEF record](https://www.d-logic.com/knowledge_base/ndef-detection-and-access-mifare-classic-mifare-plus-tags/) (AID==E103)?

([here is a handy video that explaines MAD in detail](https://www.youtube.com/watch?v=sPfP9svvCjc))

**Comment by Harry-Chen** [comment]
This repository handles only the parsing and generation of pure NDEF data. The MAD you mentioned seems out of topic?

BTW, both Android and iOS can retrieve NDEF data according to MAD ASAIK.
